config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
  }

  root 'dashboard/instagram_media#index'

  resources :after_signup, only: %i(show update)
  resources :subscriptions, only: :create

  namespace :dashboard do
    resources :instagram_media, only: %i(index create)
    resources :settings, only: :index
    resources :media do
      resources :products
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :media
  has_and_belongs_to_many :categories

  scope :persisted, -> { where.not(id: nil) }

  enum gender: %i[any male female]

  validates :name, :price, :currency, presence: true
end

app/controllers/dashboard/instagram_media_controller.rb
class Dashboard::InstagramMediaController < ApplicationController
  def index
    @media = MediaService.new(token: facebook_token, business_id: business_id).facebook_media_hash
  end

  def create
    if params[:media_collection].nil?
      redirect_to(dashboard_instagram_media_path, alert: 'Something went wrong')
    else
      save_with_status(params[:status])
    end
  end

  private

  def facebook_token
    current_user.token
  end

  def business_id
    current_retailer.business_id
  end

  def save_with_status(status)
    MediaService.new(status: status, media_collection: params[:media_collection], current_retailer: current_retailer).create_media_collection
    redirect_to dashboard_media_index_path(status: status), notice: 'Media were successfully saved.'
  end
end

app/controllers/dashboard/media_controller.rb
class Dashboard::MediaController < ApplicationController
  def index
    @media = Media.where(status: params[:status])
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
  def new
    @product = media.products.new
    fetch_product if provider_url
  end

  def create
    @product = media.products.new(product_params)
    @product.save
    render :create, layout: false
  end

  def destroy
    Product.find(params[:id]).destroy
    render :destroy, layout: false
  end

  private

  def fetch_product
    attrs = ProductFetcher::Service.new(provider_url, current_user.current_retailer).parse
    @product.assign_attributes(attrs)
  end

  def provider_url
    params[:product]&.[](:provider_url)
  end

  def media
    @media ||= Media.find(params[:media_id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :original_price, :currency, :image_url, :canonical_url, :brand, :gender, category_ids: [])
  end
end

app/controllers/dashboard/settings_controller.rb
class Dashboard::SettingsController < ApplicationController
  def index; end
end

app/helpers/dashboard/media_helper.rb
module Dashboard::MediaHelper
  def current_class?(test_path)
    return 'active' if request.fullpath == test_path
  end
end

app/views/dashboard/products/_category.slim
div.form-check.ml-3
  = check_box_tag 'product[category_ids][]', category.id, false, class: 'form-check-input check_boxes optional', id: "product_category_ids_#{category.id}"
  = label_tag "product_category_ids_#{category.id}", category.name, class: 'collection_check_boxes'
  - if category.subcategories.any?
    - category.subcategories.each do |subcategory|
      = render partial: 'category', locals: { category: subcategory }

app/views/dashboard/products/_product.slim
.row.border.border-secondary.rounded.mb-3.p-2 data-product="#{product.id}"
  .col-md-4
    = image_tag product.image_url, class: 'img-fluid' if product.image_url
  .col-md-8
    .row
      p.font-weight-bold = product.name
    .row
      span.font-weight-bold Price:
      span = "#{product.price} #{product.currency}"
    .row
      span.font-weight-bold Brand:
      span = product.brand
    .row
      span.font-weight-bold Categories:
      p = product.categories.map(&:name).join(', ')
    .row
      span.font-weight-bold Gender:
      p = product.gender
    - if product.description.present?
      .row
        span.font-weight-bold Description:
        p = product.description
    .row.d-block.text-right
      = link_to 'To Shop', product.canonical_url, class: 'btn btn-secondary mr-3', target: :_blank
      = link_to 'Remove', dashboard_media_product_path(product.media, product), method: :delete, remote: true, class: 'btn btn-danger'

app/views/dashboard/products/new.slim
.row
  .col-md-6
    = image_tag @media.media_url, class: 'img-fluid'
    span = @media.caption
    h2 Products:
    div data-products=''
      = render partial: 'product', collection: @media.products.persisted
  .col-md-6
    = simple_form_for(@product, url: new_dashboard_media_product_path, method: :get) do |f|
      = f.input :provider_url, as: :string
      = f.button :submit, 'Lookup Product'
    = simple_form_for(@product, url: dashboard_media_products_path, remote: true, html: { data: { product_form: '' } }) do |f|
      = f.input :name
      = f.input :description, as: :text
      .row
        .col-4
          = f.input :price
        .col-4
          = f.input :original_price
        .col-4
          = f.input :currency
      = f.input :image_url, as: :string, input_html: { data: { behavior: 'imageInput' } }
      img data-preview=''
      = f.input :canonical_url, as: :string
      .row
        .col-4
          = f.input :brand
        .col-4
          = f.input :availability
        .col-4
          = f.input :gender, collection: Product.genders.keys, include_blank: false
      fieldset.form-group.check_boxes.optional.product_categories
        legend.col-form-label.pt-0 Categories
        = hidden_field_tag 'product[category_ids][]'
        - Category.where(parent_id: nil).each do |category|
          = render partial: 'category', locals: { category: category }
      = f.button :submit