config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
  }

  root 'dashboard/instagram_media#index'

  resources :after_signup, only: %i(show update)
  resources :subscriptions, only: :create

  namespace :dashboard do
    resources :instagram_media, only: %i(index create)
    resources :settings, only: :index
    resources :media do
      resources :products
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carousel_album.rb
class CarouselAlbum < Media
  def self.from_hash(hash)
    new(
      status: hash['status'],
      media_url: hash['carousel_item']['media_url'],
      caption: hash['caption'],
      created_time: hash['timestamp'],
      permalink: hash['permalink'],
      username: hash['username'],
      instagram_id: hash['carousel_item']['id'],
      media_type: hash['carousel_item']['media_type']
    )
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :parent, class_name: 'Category', optional: true
  has_many :subcategories, class_name: 'Category', foreign_key: :parent_id, dependent: :destroy
  has_and_belongs_to_many :products
end

app/models/image.rb
class Image < Media
  def self.from_hash(hash)
    new(
      status: hash['status'],
      media_url: hash['media_url'],
      caption: hash['caption'],
      created_time: hash['timestamp'],
      permalink: hash['permalink'],
      username: hash['username'],
      instagram_id: hash['id'],
      media_type: hash['media_type']
    )
  end
end

app/models/media.rb
class Media < ApplicationRecord
  belongs_to :retailer
  has_many :products

  enum status: { pending: 0, active: 1, rejected: 2 }

  scope :image, -> { where(type: 'Image') }
  scope :video, -> { where(type: 'Video') }
  scope :carousel_album, -> { where(type: 'CarouselAlbum') }

  validates :instagram_id, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :media
  has_and_belongs_to_many :categories

  scope :persisted, -> { where.not(id: nil) }

  enum gender: %i[any male female]

  validates :name, :price, :currency, presence: true
end

app/models/retailer.rb
class Retailer < ApplicationRecord
  belongs_to :user
  has_one :subscription, dependent: :destroy
  has_many :media, dependent: :destroy

  accepts_nested_attributes_for :subscription
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :retailer

  enum plan_type: %i[essentials complete enterprise]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :retailers, dependent: :destroy
  has_one :current_retailer, -> { where(current: true) }, class_name: 'Retailer'
  has_one :subscription, through: :current_retailer

  accepts_nested_attributes_for :retailers
  accepts_nested_attributes_for :current_retailer

  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.token = auth.credentials.token
      user.name = auth.info.name
    end
  end

  private

  def password_required?
    false
  end
end

app/models/video.rb
class Video < Media
  def self.from_hash(hash) # rubocop:disable Metrics/MethodLength
    new(
      status: hash['status'],
      media_url: hash['media_url'],
      thumbnail_url: hash['thumbnail_url'],
      caption: hash['caption'],
      created_time: hash['timestamp'],
      permalink: hash['permalink'],
      username: hash['username'],
      instagram_id: hash['id'],
      media_type: hash['media_type']
    )
  end
end

app/controllers/after_signup_controller.rb
class AfterSignupController < ApplicationController
  include Wicked::Wizard

  before_action :authenticate_user!
  skip_before_action :verify_user_steps!

  steps :business_account, :subscription_plan, :card_addition, :finish

  def show
    @user = current_user
    skip_steps
    case step
    when :business_account
      @retailers ||= retailers
    when :subscription_plan
      @plans ||= plans
    end

    render_wizard
  end

  def update
    @user = current_user
    case step
    when :business_account
      RetailerService.new(user: current_user, params: params[:user][:retailer][:business_id]).set_retailer
    when :subscription_plan
      @user.assign_attributes(user_params)
    end
    render_wizard @user
  end

  private

  def redirect_to_finish_wizard(_options, _params)
    redirect_to root_path, notice: 'Thank you for signing up.'
  end

  def user_params
    params.require(:user).permit(:email, current_retailer_attributes: [:id, subscription_attributes: %i[plan_token plan_type]])
  end

  def retailers
    RetailerService.new(token: current_user.token).build_retailers
  end

  def plans
    Pin::Plan.all.sort { |plan| plan['amount'].to_i }
  end

  def skip_steps
    case step
    when :business_account
      skip_step if current_retailer
    when :subscription_plan, :card_addition
      skip_step if active_subsciption?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :verify_user_steps!

  def active_subsciption?
    current_retailer&.subscription&.active
  end

  def current_retailer
    current_user&.current_retailer
  end

  private

  def verify_user_steps!
    return if devise_controller?

    return if active_subsciption?

    redirect_to after_signup_path(:business_account)
  end
end

app/controllers/dashboard/media_controller.rb
class Dashboard::MediaController < ApplicationController
  def index
    @media = Media.where(status: params[:status])
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
  def new
    @product = media.products.new
    fetch_product if provider_url
  end

  def create
    @product = media.products.new(product_params)
    @product.save
    render :create, layout: false
  end

  def destroy
    Product.find(params[:id]).destroy
    render :destroy, layout: false
  end

  private

  def fetch_product
    attrs = ProductFetcher::Service.new(provider_url, current_user.current_retailer).parse
    @product.assign_attributes(attrs)
  end

  def provider_url
    params[:product]&.[](:provider_url)
  end

  def media
    @media ||= Media.find(params[:media_id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :original_price, :currency, :image_url, :canonical_url, :brand, :gender, category_ids: [])
  end
end

app/controllers/dashboard/settings_controller.rb
class Dashboard::SettingsController < ApplicationController
  def index; end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  skip_before_action :verify_user_steps!

  def create
    errors = SubscriptionService.new(current_user, params).subscribe

    render json: { errors: errors, url: after_signup_path(:finish) }
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
    set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def destroy
    current_user.retailers.update_all(current: false)
    super
  end
end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
  def price(plan)
    "#{plan['amount'].to_i / 100}#{plan['currency']}"
  end

  def plan_params(plan)
    { user: { current_retailer_attributes: { id: current_user.current_retailer.id,
                                             subscription_attributes: { plan_token: plan['token'],
                                                                        plan_type: plan['name'].split.first.downcase } } } }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/media_helper.rb
module Dashboard::MediaHelper
  def current_class?(test_path)
    return 'active' if request.fullpath == test_path
  end
end

app/views/after_signup/business_account.slim
h1 Business account

= form_for @user, url: wizard_path, method: :put do |f|
  = f.fields_for current_user.retailers.new do |r|
    = r.select :business_id, options_for_select(@retailers)

    = f.submit 'Next'

app/views/after_signup/card_addition.slim
h1 Card addition
= form_tag(wizard_path, method: :put, class: 'pin', data: { behavior: 'cardForm', api_key: Rails.application.credentials[:pin_payments_publishable] }) do
  .errors style="display:none"
    h3
    ul
  .form-row
    legend Billing
    .form-group.col-4
      label for='email' Email
      = email_field_tag(:email, '', { id: 'email', class: 'form-control' })
    .form-group.col-4
      label for="address-line1"  Address 1
      = text_field_tag(nil, nil, { id: 'address-line1', class: 'form-control' })
    .form-group.col-4
      label for="address-line2"  Address 2
      = text_field_tag(nil, nil, { id: 'address-line2', class: 'form-control' })
    .form-group.col-4
      label for="address-city"  City
      = text_field_tag(nil, nil, { id: 'address-city', class: 'form-control' })
    .form-group.col-2
      label for="address-state"  State
      = text_field_tag(nil, nil, { id: 'address-state', class: 'form-control' })
    .form-group.col-2
      label for="address-postcode"  Postcode
      = text_field_tag(nil, nil, { id: 'address-postcode', class: 'form-control' })
    .form-group.col-4
      label for="address-country"  Country
      = text_field_tag(nil, nil, { id: 'address-country', class: 'form-control' })
  .form-row
    legend Payment
    .form-group.col-6
      label for="cc-number"  Credit Card Number
      = text_field_tag(nil, nil, { id: 'cc-number', class: 'form-control' })
    .form-group.col-6
      label for="cc-name"  Name on Card
      = text_field_tag(nil, nil, { id: 'cc-name', class: 'form-control' })
    .form-group.col-4
      label for="cc-expiry-month"  Expiry Month
      = text_field_tag(nil, nil, { id: 'cc-expiry-month', class: 'form-control' })
    .form-group.col-4
      label for="cc-expiry-year"  Expiry Year
      = text_field_tag(nil, nil, { id: 'cc-expiry-year', class: 'form-control' })
    .form-group.col-4
      label for="cc-cvc"  CVC
      = text_field_tag(nil, nil, { id: 'cc-cvc', class: 'form-control' })
  = submit_tag('Save Changes', { class: 'btn' })

app/views/after_signup/finish.slim
h1 Success

app/views/after_signup/subscription_plan.slim
h1 Subscription plan
.row
  - @plans.each do |plan|
    .plan.col-4
      h2 = plan['name']
      span = price(plan)
      = button_to 'Subscribe', wizard_path(:subscription_plan, plan_params(plan)), class: 'btn', method: :put

app/views/application/_flash_messages.slim
#flash
  - flash.select { |_k, v| v.is_a? String }.each do |type, message|
    div class="alert alert-dismissable bg-#{type == 'alert' ? 'danger' : 'success'}" role="alert"
      button.close aria-hidden="true" data-dismiss="alert" type="button"
        i.fa.fa-times
      = message

app/views/application/_head.slim
head
  title TaggdLite
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'https://cdn.pinpayments.com/pin.v2.js' 

  

app/views/application/_header.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark.mb-4
  .container
    a.navbar-brand href="#"  Tagged
    button.navbar-toggler.collapsed aria-controls="navbarCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarCollapse" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
    #navbarCollapse.navbar-collapse.collapse style=""
      ul.navbar-nav.mr-auto
        li.nav-item.active
          a.nav-link href="#"
            | Home
            span.sr-only (current)
        li.nav-item
          a.nav-link href="#"  Link
        li.nav-item
          a.nav-link.disabled href="#"  Disabled
      - if current_user&.current_retailer
        ul.navbar.navbar-nav.navbar-right
          li.nav-item.dropdown
            a.nav-link.dropdown-toggle#navbarDropdown data-toggle='dropdown' role='button' href='#' #{current_user.current_retailer.name}
            .dropdown-menu aria-labelledby='navbarDropdown'
              = link_to 'Instagram Media', dashboard_instagram_media_path, class: 'dropdown-item'
              = link_to 'Settings', dashboard_settings_path, class: 'dropdown-item'